//User Actions Types
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const SET_USER = "SET_USER";
export const SET_DEPARTMENTS = "SET_DEPARTMENTS";
export const SET_USERS = "SET_USERS";

export const SET_REQUEST = "SET_REQUEST";
export const ADD_PENDING_REQUEST = "ADD_PENDING_REQUEST";
export const ADD_APPROVED_REQUEST = "ADD_APPROVED_REQUEST";
export const REMOVE_PENDING_REQUEST = "REMOVE_PENDING_REQUEST";
export const ADD_INCOMING_REQUEST = "ADD_INCOMING_REQUEST";
export const REMOVE_INCOMING_REQUEST = "REMOVE_INCOMING_REQUEST";
export const SET_PENDING_REQUESTS = "SET_PENDING_REQUESTS";
export const SET_APPROVED_REQUESTS = "SET_APPROVED_REQUESTS";
export const SET_APPROVAL_REQUESTS = "SET_APPROVAL_REQUESTS";

